name: Udemi

services:
  minio:
    image: bitnami/minio:latest
    container_name: minio_udemi
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@2024
    volumes:
      - ./data:/bitnami/minio/data
    ports:
      - '9000:9000'
      - '9001:9001'
    command: minio server /bitnami/minio/data --console-address ":9001"

  postgresql_udemi:
    container_name: postgresql_udemi
    image: postgres:16.2
    environment:
      - POSTGRES_USER=udemi
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=udemi
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: on-failure
    ports:
      - "5432:5432"

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    container_name: udemi_elasticsearch
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'

  redis:
    image: redis:6.2.7
    container_name: redis_udemi
    restart: on-failure
    ports:
      - "6379:6379"

volumes:
  data:
    driver: local